# Generated by Django 4.1 on 2025-02-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productkeys",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
