# Generated by Django 4.1 on 2025-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order_created_order_created_by_order_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
