# Generated by Django 4.1 on 2025-02-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlines",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Cards",
                related_query_name="Cards",
                to="products.order",
            ),
        ),
    ]
