# Generated by Django 4.1 on 2025-02-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="product_id",
        ),
    ]
