# Generated by Django 4.1 on 2025-03-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_product_order_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlines",
            name="trxId",
        ),
    ]
