# Generated by Django 4.1 on 2025-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productkeys",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
