# Generated by Django 4.1 on 2025-03-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productkeys_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="productkeys",
            name="used_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_product_keys",
                related_query_name="used_product_key",
                to="products.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
