# Generated by Django 4.1 on 2025-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_productkeys_used_order_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productkeys",
            options={"ordering": ["-used_at", "-created"]},
        ),
        migrations.AddField(
            model_name="productkeys",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
