# Generated by Django 4.1 on 2025-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productkeys_options_productkeys_used_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productkeys",
            name="serial_no",
        ),
        migrations.AddField(
            model_name="productkeys",
            name="serial_no_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
